// The one authoritative list. Every category lives here, nested under its section.
// Adding a category means adding it here, nowhere else, so there is exactly one
// source of truth and every comment's `category` is checked against it at compile time.
export const CATEGORIES_BY_SECTION = {
  behavior: [
    'self-control',
    'peer-relationships',
    'focus-and-attention',
    'participation',
    'leadership',
    'independence',
    'following-directions',
    'effort-and-motivation',
  ],
  adhd: [
    'attention-and-focus',
    'impulse-control',
    'organization',
    'task-completion',
    'self-regulation-strategies',
  ],
  preschool: [
    'social-emotional-development',
    'self-help-skills',
    'play-and-cooperation',
    'early-literacy',
    'early-math',
    'gross-and-fine-motor',
  ],
  academics: [
    'reading',
    'writing',
    'math',
    'general-work-habits',
  ],
  'social-emotional': [
    'emotional-regulation',
    'empathy-and-relationships',
    'self-awareness',
    'resilience-and-growth-mindset',
  ],
} as const;

export type Section = keyof typeof CATEGORIES_BY_SECTION;
export type CategoryFor<S extends Section> = (typeof CATEGORIES_BY_SECTION)[S][number];

export const SECTION_LABELS: Record<Section, string> = {
  behavior: 'Behavior',
  adhd: 'ADHD / Attention',
  preschool: 'Preschool',
  academics: 'Academics',
  'social-emotional': 'Social-Emotional',
};

export const CATEGORY_LABELS: Record<string, string> = {
  'self-control': 'Self-control',
  'peer-relationships': 'Peer relationships',
  'focus-and-attention': 'Focus and attention',
  participation: 'Participation',
  leadership: 'Leadership',
  independence: 'Independence',
  'following-directions': 'Following directions',
  'effort-and-motivation': 'Effort and motivation',
  'attention-and-focus': 'Attention and focus',
  'impulse-control': 'Impulse control',
  organization: 'Organization',
  'task-completion': 'Task completion',
  'self-regulation-strategies': 'Self-regulation strategies',
  'social-emotional-development': 'Social-emotional development',
  'self-help-skills': 'Self-help skills',
  'play-and-cooperation': 'Play and cooperation',
  'early-literacy': 'Early literacy',
  'early-math': 'Early math',
  'gross-and-fine-motor': 'Gross and fine motor',
  reading: 'Reading',
  writing: 'Writing',
  math: 'Math',
  'general-work-habits': 'General work habits',
  'emotional-regulation': 'Emotional regulation',
  'empathy-and-relationships': 'Empathy and relationships',
  'self-awareness': 'Self-awareness',
  'resilience-and-growth-mindset': 'Resilience and growth mindset',
};

export const TONES = ['positive', 'growth'] as const;
export type Tone = (typeof TONES)[number];

export const GRADE_BANDS = ['preschool', 'k-2', '3-5', 'middle-upper'] as const;
export type GradeBand = (typeof GRADE_BANDS)[number];

export const GRADE_BAND_LABELS: Record<GradeBand, string> = {
  preschool: 'Preschool',
  'k-2': 'K-2',
  '3-5': '3-5',
  'middle-upper': 'Middle/Upper',
};

export interface Comment<S extends Section = Section> {
  id: string;
  section: S;
  category: CategoryFor<S>;
  tone: Tone;
  gradeBands: GradeBand[];
  text: string; // uses [Student] as the literal placeholder token for personalization
}

// Full library, built in approved batches (Step 6). Started from the 20
// representative samples approved 2026-07-22 for the Step 4 prototype.
// See "Report Card Comment Library - V1 Schema.md" section 7 for the content
// style guide every comment here is written and audited against, and section 10
// for the revision history behind the original sample wording.
//
// Batch log:
//   2026-07-28  behavior/self-control       +20 (21 total incl. original sample)
//   2026-07-28  behavior/peer-relationships +21 (22 total incl. original sample)
//   2026-07-28  behavior/focus-and-attention +15 (16 total incl. original sample)
//   2026-07-28  behavior/independence       +18 (18 total)
//   2026-07-28  behavior/effort-and-motivation +20 (20 total)
//   2026-07-28  behavior/participation      +19 (19 total)
//   2026-07-28  behavior/leadership         +13 (14 total incl. revised original sample)
//   2026-07-28  behavior/following-directions +14 (15 total incl. original sample)
//               BEHAVIOR SECTION COMPLETE at 145 across 8 categories.
export const REPORT_CARD_COMMENTS: Comment[] = [
  {
    id: 'behavior-positive-self-control-01',
    section: 'behavior',
    category: 'self-control',
    tone: 'positive',
    gradeBands: ['k-2', '3-5'],
    text: '[Student] consistently pauses to think before reacting, even in moments of frustration.',
  },
  {
    id: 'behavior-positive-self-control-02',
    section: 'behavior',
    category: 'self-control',
    tone: 'positive',
    gradeBands: ['k-2', '3-5'],
    text: '[Student] handles the disappointment of a game not going their way with real composure.',
  },
  {
    id: 'behavior-positive-self-control-03',
    section: 'behavior',
    category: 'self-control',
    tone: 'positive',
    gradeBands: ['k-2', '3-5', 'middle-upper'],
    text: '[Student] manages their excitement well during high-energy parts of the day, like assemblies and celebrations.',
  },
  {
    id: 'behavior-positive-self-control-04',
    section: 'behavior',
    category: 'self-control',
    tone: 'positive',
    gradeBands: ['preschool', 'k-2'],
    text: '[Student] is generally mindful of personal space and keeps their hands and body to themselves.',
  },
  {
    id: 'behavior-positive-self-control-05',
    section: 'behavior',
    category: 'self-control',
    tone: 'positive',
    gradeBands: ['k-2', '3-5'],
    text: '[Student] adjusts appropriately when plans change unexpectedly and continues with the group.',
  },
  {
    id: 'behavior-positive-self-control-06',
    section: 'behavior',
    category: 'self-control',
    tone: 'positive',
    gradeBands: ['k-2', '3-5', 'middle-upper'],
    text: '[Student] responds calmly to redirection and returns to the task appropriately.',
  },
  {
    id: 'behavior-positive-self-control-07',
    section: 'behavior',
    category: 'self-control',
    tone: 'positive',
    gradeBands: ['3-5', 'middle-upper'],
    text: 'When a peer interaction becomes frustrating, [Student] chooses not to escalate the situation.',
  },
  {
    id: 'behavior-positive-self-control-08',
    section: 'behavior',
    category: 'self-control',
    tone: 'positive',
    gradeBands: ['preschool', 'k-2'],
    text: '[Student] waits their turn patiently, even when they are eager to share.',
  },
  {
    id: 'behavior-positive-self-control-09',
    section: 'behavior',
    category: 'self-control',
    tone: 'positive',
    gradeBands: ['preschool', 'k-2'],
    text: '[Student] moves between activities calmly and is ready to begin the next task.',
  },
  {
    id: 'behavior-positive-self-control-10',
    section: 'behavior',
    category: 'self-control',
    tone: 'positive',
    gradeBands: ['k-2', '3-5'],
    text: 'When [Student] feels frustrated, they express it in words rather than actions.',
  },
  {
    id: 'behavior-positive-self-control-11',
    section: 'behavior',
    category: 'self-control',
    tone: 'positive',
    gradeBands: ['3-5', 'middle-upper'],
    text: 'When a request is not granted or an alternative is offered, [Student] accepts it with maturity.',
  },
  {
    id: 'behavior-growth-self-control-01',
    section: 'behavior',
    category: 'self-control',
    tone: 'growth',
    gradeBands: ['k-2', '3-5'],
    text: 'Handling disappointment when things do not go their way is an area [Student] is still developing.',
  },
  {
    id: 'behavior-growth-self-control-02',
    section: 'behavior',
    category: 'self-control',
    tone: 'growth',
    gradeBands: ['k-2', '3-5'],
    text: 'During high-energy moments, [Student] is working on keeping their excitement at a manageable level.',
  },
  {
    id: 'behavior-growth-self-control-03',
    section: 'behavior',
    category: 'self-control',
    tone: 'growth',
    gradeBands: ['preschool', 'k-2'],
    text: '[Student] is learning to keep their hands and body to themselves, particularly in close quarters like the carpet or line.',
  },
  {
    id: 'behavior-growth-self-control-04',
    section: 'behavior',
    category: 'self-control',
    tone: 'growth',
    gradeBands: ['k-2', '3-5'],
    text: 'Adjusting to unexpected changes in the schedule is an area [Student] is continuing to develop.',
  },
  {
    id: 'behavior-growth-self-control-05',
    section: 'behavior',
    category: 'self-control',
    tone: 'growth',
    gradeBands: ['k-2', '3-5', 'middle-upper'],
    text: 'Responding calmly to redirection is an ongoing goal for [Student].',
  },
  {
    id: 'behavior-growth-self-control-06',
    section: 'behavior',
    category: 'self-control',
    tone: 'growth',
    gradeBands: ['3-5', 'middle-upper'],
    text: 'When a peer interaction becomes upsetting, [Student] is working on walking away or seeking adult support rather than reacting in the moment.',
  },
  {
    id: 'behavior-growth-self-control-07',
    section: 'behavior',
    category: 'self-control',
    tone: 'growth',
    gradeBands: ['preschool', 'k-2'],
    text: 'Waiting for a turn without interrupting is a skill [Student] continues to build.',
  },
  {
    id: 'behavior-growth-self-control-08',
    section: 'behavior',
    category: 'self-control',
    tone: 'growth',
    gradeBands: ['k-2', '3-5'],
    text: '[Student] is working on expressing frustration in words and maintaining appropriate physical boundaries when upset.',
  },
  {
    id: 'behavior-growth-self-control-09',
    section: 'behavior',
    category: 'self-control',
    tone: 'growth',
    gradeBands: ['3-5', 'middle-upper'],
    text: 'Accepting an answer of no without arguing is something [Student] is continuing to practice.',
  },
  {
    id: 'behavior-growth-self-control-10',
    section: 'behavior',
    category: 'self-control',
    tone: 'growth',
    gradeBands: ['preschool', 'k-2'],
    text: 'Moving between activities can be difficult for [Student]; a brief heads-up before a transition supports a smoother shift.',
  },
  {
    id: 'behavior-growth-focus-and-attention-01',
    section: 'behavior',
    category: 'focus-and-attention',
    tone: 'growth',
    gradeBands: ['3-5', 'middle-upper'],
    text: 'Staying focused during longer independent tasks is still developing; [Student] does best with a clear stopping point in sight.',
  },
  {
    id: 'behavior-positive-focus-and-attention-01',
    section: 'behavior',
    category: 'focus-and-attention',
    tone: 'positive',
    gradeBands: ['k-2', '3-5', 'middle-upper'],
    text: '[Student] stays focused during independent work and uses the full work period productively.',
  },
  {
    id: 'behavior-positive-focus-and-attention-02',
    section: 'behavior',
    category: 'focus-and-attention',
    tone: 'positive',
    gradeBands: ['k-2', '3-5', 'middle-upper'],
    text: 'During whole-group instruction, [Student] remains engaged and follows along with the lesson.',
  },
  {
    id: 'behavior-positive-focus-and-attention-03',
    section: 'behavior',
    category: 'focus-and-attention',
    tone: 'positive',
    gradeBands: ['k-2', '3-5'],
    text: '[Student] returns to their work quickly after an interruption.',
  },
  {
    id: 'behavior-positive-focus-and-attention-04',
    section: 'behavior',
    category: 'focus-and-attention',
    tone: 'positive',
    gradeBands: ['3-5', 'middle-upper'],
    text: '[Student] stays on task when working alongside a partner or small group.',
  },
  {
    id: 'behavior-positive-focus-and-attention-05',
    section: 'behavior',
    category: 'focus-and-attention',
    tone: 'positive',
    gradeBands: ['3-5', 'middle-upper'],
    text: 'Even in less-preferred subjects, [Student] stays engaged with the task at hand.',
  },
  {
    id: 'behavior-positive-focus-and-attention-06',
    section: 'behavior',
    category: 'focus-and-attention',
    tone: 'positive',
    gradeBands: ['k-2', '3-5', 'middle-upper'],
    text: '[Student] maintains attention on their work despite nearby activity.',
  },
  {
    id: 'behavior-positive-focus-and-attention-07',
    section: 'behavior',
    category: 'focus-and-attention',
    tone: 'positive',
    gradeBands: ['3-5', 'middle-upper'],
    text: '[Student] sustains attention through longer lessons and multi-part activities.',
  },
  {
    id: 'behavior-positive-focus-and-attention-08',
    section: 'behavior',
    category: 'focus-and-attention',
    tone: 'positive',
    gradeBands: ['preschool', 'k-2', '3-5'],
    text: '[Student] stays attentive during the last part of the school day.',
  },
  {
    id: 'behavior-growth-focus-and-attention-02',
    section: 'behavior',
    category: 'focus-and-attention',
    tone: 'growth',
    gradeBands: ['k-2', '3-5', 'middle-upper'],
    text: 'During longer whole-group lessons, maintaining attention through the final portion remains challenging for [Student].',
  },
  {
    id: 'behavior-growth-focus-and-attention-03',
    section: 'behavior',
    category: 'focus-and-attention',
    tone: 'growth',
    gradeBands: ['k-2', '3-5'],
    text: '[Student] is working on returning to a task promptly after an interruption.',
  },
  {
    id: 'behavior-growth-focus-and-attention-04',
    section: 'behavior',
    category: 'focus-and-attention',
    tone: 'growth',
    gradeBands: ['3-5', 'middle-upper'],
    text: 'Maintaining focus during partner work is an ongoing goal for [Student].',
  },
  {
    id: 'behavior-growth-focus-and-attention-05',
    section: 'behavior',
    category: 'focus-and-attention',
    tone: 'growth',
    gradeBands: ['3-5', 'middle-upper'],
    text: 'Attention during less-preferred subjects is an area [Student] continues to build.',
  },
  {
    id: 'behavior-growth-focus-and-attention-06',
    section: 'behavior',
    category: 'focus-and-attention',
    tone: 'growth',
    gradeBands: ['k-2', '3-5'],
    text: '[Student] is working on staying with a task when there is activity nearby.',
  },
  {
    id: 'behavior-growth-focus-and-attention-07',
    section: 'behavior',
    category: 'focus-and-attention',
    tone: 'growth',
    gradeBands: ['preschool', 'k-2', '3-5'],
    text: 'Holding attention during the last part of the day is an area [Student] is continuing to develop.',
  },
  {
    id: 'behavior-growth-focus-and-attention-08',
    section: 'behavior',
    category: 'focus-and-attention',
    tone: 'growth',
    gradeBands: ['k-2', '3-5', 'middle-upper'],
    text: '[Student] is working on tracking the speaker during class discussions and lessons.',
  },
  {
    id: 'behavior-positive-peer-relationships-01',
    section: 'behavior',
    category: 'peer-relationships',
    tone: 'positive',
    gradeBands: ['k-2', '3-5', 'middle-upper'],
    text: '[Student] works patiently and fairly with classmates and is a dependable partner during group activities.',
  },
  {
    id: 'behavior-positive-peer-relationships-02',
    section: 'behavior',
    category: 'peer-relationships',
    tone: 'positive',
    gradeBands: ['k-2', '3-5', 'middle-upper'],
    text: '[Student] works comfortably with a wide range of classmates, not only their closest friends.',
  },
  {
    id: 'behavior-positive-peer-relationships-03',
    section: 'behavior',
    category: 'peer-relationships',
    tone: 'positive',
    gradeBands: ['k-2', '3-5'],
    text: '[Student] is a welcoming partner who encourages others to contribute.',
  },
  {
    id: 'behavior-positive-peer-relationships-04',
    section: 'behavior',
    category: 'peer-relationships',
    tone: 'positive',
    gradeBands: ['preschool', 'k-2', '3-5'],
    text: 'When someone is left out of an activity, [Student] notices and invites them in.',
  },
  {
    id: 'behavior-positive-peer-relationships-05',
    section: 'behavior',
    category: 'peer-relationships',
    tone: 'positive',
    gradeBands: ['3-5', 'middle-upper'],
    text: '[Student] works through disagreements with classmates independently, seeking adult support when it is genuinely needed.',
  },
  {
    id: 'behavior-positive-peer-relationships-06',
    section: 'behavior',
    category: 'peer-relationships',
    tone: 'positive',
    gradeBands: ['3-5', 'middle-upper'],
    text: '[Student] can disagree with a classmate respectfully and keep the conversation going.',
  },
  {
    id: 'behavior-positive-peer-relationships-07',
    section: 'behavior',
    category: 'peer-relationships',
    tone: 'positive',
    gradeBands: ['preschool', 'k-2'],
    text: '[Student] shares materials and workspace generously.',
  },
  {
    id: 'behavior-positive-peer-relationships-08',
    section: 'behavior',
    category: 'peer-relationships',
    tone: 'positive',
    gradeBands: ['3-5', 'middle-upper'],
    text: '[Student] notices social cues from classmates and adjusts their approach accordingly.',
  },
  {
    id: 'behavior-positive-peer-relationships-09',
    section: 'behavior',
    category: 'peer-relationships',
    tone: 'positive',
    gradeBands: ['k-2', '3-5', 'middle-upper'],
    text: '[Student] helped new classmates feel welcome this year.',
  },
  {
    id: 'behavior-positive-peer-relationships-10',
    section: 'behavior',
    category: 'peer-relationships',
    tone: 'positive',
    gradeBands: ['3-5', 'middle-upper'],
    text: 'In group work, [Student] listens as much as they contribute.',
  },
  {
    id: 'behavior-positive-peer-relationships-11',
    section: 'behavior',
    category: 'peer-relationships',
    tone: 'positive',
    gradeBands: ['k-2', '3-5'],
    text: 'When a classmate needs something clarified, [Student] explains it without taking over their work.',
  },
  {
    id: 'behavior-positive-peer-relationships-12',
    section: 'behavior',
    category: 'peer-relationships',
    tone: 'positive',
    gradeBands: ['3-5', 'middle-upper'],
    text: 'When a group decision does not go their way, [Student] supports the outcome and stays engaged.',
  },
  {
    id: 'behavior-positive-peer-relationships-13',
    section: 'behavior',
    category: 'peer-relationships',
    tone: 'positive',
    gradeBands: ['3-5', 'middle-upper'],
    text: '[Student] accepts suggestions and feedback from classmates with an open mind.',
  },
  {
    id: 'behavior-growth-peer-relationships-01',
    section: 'behavior',
    category: 'peer-relationships',
    tone: 'growth',
    gradeBands: ['k-2', '3-5', 'middle-upper'],
    text: 'Working with classmates outside their usual group is an area [Student] is continuing to develop.',
  },
  {
    id: 'behavior-growth-peer-relationships-02',
    section: 'behavior',
    category: 'peer-relationships',
    tone: 'growth',
    gradeBands: ['3-5', 'middle-upper'],
    text: '[Student] is working on resolving disagreements with peers before they need adult support.',
  },
  {
    id: 'behavior-growth-peer-relationships-03',
    section: 'behavior',
    category: 'peer-relationships',
    tone: 'growth',
    gradeBands: ['3-5', 'middle-upper'],
    text: 'Disagreeing respectfully, rather than insisting on their own view, is a skill [Student] continues to build.',
  },
  {
    id: 'behavior-growth-peer-relationships-04',
    section: 'behavior',
    category: 'peer-relationships',
    tone: 'growth',
    gradeBands: ['preschool', 'k-2'],
    text: 'Sharing materials and workspace is an ongoing goal for [Student].',
  },
  {
    id: 'behavior-growth-peer-relationships-05',
    section: 'behavior',
    category: 'peer-relationships',
    tone: 'growth',
    gradeBands: ['k-2', '3-5'],
    text: '[Student] is learning to notice when a classmate wants a turn to talk.',
  },
  {
    id: 'behavior-growth-peer-relationships-06',
    section: 'behavior',
    category: 'peer-relationships',
    tone: 'growth',
    gradeBands: ['3-5', 'middle-upper'],
    text: "In group work, [Student] is working on making room for others' ideas alongside their own.",
  },
  {
    id: 'behavior-growth-peer-relationships-07',
    section: 'behavior',
    category: 'peer-relationships',
    tone: 'growth',
    gradeBands: ['k-2', '3-5'],
    text: '[Student] is working on responding flexibly when peer groupings or activity arrangements change.',
  },
  {
    id: 'behavior-growth-peer-relationships-08',
    section: 'behavior',
    category: 'peer-relationships',
    tone: 'growth',
    gradeBands: ['3-5', 'middle-upper'],
    text: '[Student] is working on moving forward after a disagreement so it does not affect later interactions.',
  },
  {
    id: 'behavior-growth-peer-relationships-09',
    section: 'behavior',
    category: 'peer-relationships',
    tone: 'growth',
    gradeBands: ['k-2', '3-5', 'middle-upper'],
    text: 'Keeping a calm tone of voice during disagreements is a skill [Student] continues to develop.',
  },
  {
    id: 'behavior-growth-following-directions-01',
    section: 'behavior',
    category: 'following-directions',
    tone: 'growth',
    gradeBands: ['k-2'],
    text: 'Multi-step directions can be challenging for [Student]; giving one instruction at a time seems to be helping them stay focused and complete each step.',
  },
  {
    id: 'behavior-positive-following-directions-01',
    section: 'behavior',
    category: 'following-directions',
    tone: 'positive',
    gradeBands: ['preschool', 'k-2', '3-5'],
    text: '[Student] follows spoken directions and begins the task accordingly.',
  },
  {
    id: 'behavior-positive-following-directions-02',
    section: 'behavior',
    category: 'following-directions',
    tone: 'positive',
    gradeBands: ['3-5', 'middle-upper'],
    text: '[Student] uses written directions independently to work through a task.',
  },
  {
    id: 'behavior-positive-following-directions-03',
    section: 'behavior',
    category: 'following-directions',
    tone: 'positive',
    gradeBands: ['k-2', '3-5'],
    text: '[Student] refers to a model or example to guide their work.',
  },
  {
    id: 'behavior-positive-following-directions-04',
    section: 'behavior',
    category: 'following-directions',
    tone: 'positive',
    gradeBands: ['k-2', '3-5', 'middle-upper'],
    text: '[Student] follows multi-step directions and completes each step in order.',
  },
  {
    id: 'behavior-positive-following-directions-05',
    section: 'behavior',
    category: 'following-directions',
    tone: 'positive',
    gradeBands: ['3-5', 'middle-upper'],
    text: '[Student] learns unfamiliar procedures and applies them accurately.',
  },
  {
    id: 'behavior-positive-following-directions-06',
    section: 'behavior',
    category: 'following-directions',
    tone: 'positive',
    gradeBands: ['preschool', 'k-2', '3-5'],
    text: '[Student] follows directions given during transitions between activities.',
  },
  {
    id: 'behavior-positive-following-directions-07',
    section: 'behavior',
    category: 'following-directions',
    tone: 'positive',
    gradeBands: ['k-2', '3-5', 'middle-upper'],
    text: '[Student] asks for clarification when part of a direction is unclear.',
  },
  {
    id: 'behavior-positive-following-directions-08',
    section: 'behavior',
    category: 'following-directions',
    tone: 'positive',
    gradeBands: ['3-5', 'middle-upper'],
    text: '[Student] rereads the directions before asking for help.',
  },
  {
    id: 'behavior-growth-following-directions-02',
    section: 'behavior',
    category: 'following-directions',
    tone: 'growth',
    gradeBands: ['k-2', '3-5'],
    text: '[Student] is working on following spoken directions throughout a task.',
  },
  {
    id: 'behavior-growth-following-directions-03',
    section: 'behavior',
    category: 'following-directions',
    tone: 'growth',
    gradeBands: ['3-5', 'middle-upper'],
    text: 'Using written directions independently is an area [Student] is continuing to develop.',
  },
  {
    id: 'behavior-growth-following-directions-04',
    section: 'behavior',
    category: 'following-directions',
    tone: 'growth',
    gradeBands: ['k-2', '3-5'],
    text: 'Referring back to a model or example while working is a strategy [Student] is continuing to develop.',
  },
  {
    id: 'behavior-growth-following-directions-05',
    section: 'behavior',
    category: 'following-directions',
    tone: 'growth',
    gradeBands: ['k-2', '3-5', 'middle-upper'],
    text: '[Student] is working on asking for clarification when part of a direction is unclear.',
  },
  {
    id: 'behavior-growth-following-directions-06',
    section: 'behavior',
    category: 'following-directions',
    tone: 'growth',
    gradeBands: ['k-2', '3-5'],
    text: 'When a familiar procedure changes, [Student] may need time to adjust to the new steps.',
  },
  {
    id: 'behavior-growth-following-directions-07',
    section: 'behavior',
    category: 'following-directions',
    tone: 'growth',
    gradeBands: ['3-5', 'middle-upper'],
    text: 'Identifying the key steps in a set of directions is a skill [Student] continues to build.',
  },
  {
    id: 'behavior-positive-leadership-01',
    section: 'behavior',
    category: 'leadership',
    tone: 'positive',
    gradeBands: ['middle-upper'],
    text: 'When group work stalls, [Student] helps the group identify next steps and move forward.',
  },
  {
    id: 'behavior-positive-leadership-02',
    section: 'behavior',
    category: 'leadership',
    tone: 'positive',
    gradeBands: ['k-2', '3-5', 'middle-upper'],
    text: '[Student] models classroom expectations through their own actions.',
  },
  {
    id: 'behavior-positive-leadership-03',
    section: 'behavior',
    category: 'leadership',
    tone: 'positive',
    gradeBands: ['preschool', 'k-2', '3-5'],
    text: '[Student] follows through reliably on classroom responsibilities.',
  },
  {
    id: 'behavior-positive-leadership-04',
    section: 'behavior',
    category: 'leadership',
    tone: 'positive',
    gradeBands: ['3-5', 'middle-upper'],
    text: '[Student] invites ideas from everyone in the group while helping guide the work.',
  },
  {
    id: 'behavior-positive-leadership-05',
    section: 'behavior',
    category: 'leadership',
    tone: 'positive',
    gradeBands: ['3-5', 'middle-upper'],
    text: 'When a group plan needs adjusting, [Student] helps revise it so the group can move forward.',
  },
  {
    id: 'behavior-positive-leadership-06',
    section: 'behavior',
    category: 'leadership',
    tone: 'positive',
    gradeBands: ['3-5', 'middle-upper'],
    text: '[Student] raises concerns respectfully and works toward fair solutions.',
  },
  {
    id: 'behavior-positive-leadership-07',
    section: 'behavior',
    category: 'leadership',
    tone: 'positive',
    gradeBands: ['k-2', '3-5', 'middle-upper'],
    text: 'When given a role in a group, [Student] follows through on its responsibilities.',
  },
  {
    id: 'behavior-positive-leadership-08',
    section: 'behavior',
    category: 'leadership',
    tone: 'positive',
    gradeBands: ['3-5', 'middle-upper'],
    text: '[Student] steps back and gives classmates a turn to lead.',
  },
  {
    id: 'behavior-growth-leadership-01',
    section: 'behavior',
    category: 'leadership',
    tone: 'growth',
    gradeBands: ['3-5', 'middle-upper'],
    text: 'Helping a group decide on next steps is an area [Student] is continuing to develop.',
  },
  {
    id: 'behavior-growth-leadership-02',
    section: 'behavior',
    category: 'leadership',
    tone: 'growth',
    gradeBands: ['k-2', '3-5', 'middle-upper'],
    text: '[Student] is working on modeling classroom expectations consistently for others.',
  },
  {
    id: 'behavior-growth-leadership-03',
    section: 'behavior',
    category: 'leadership',
    tone: 'growth',
    gradeBands: ['preschool', 'k-2', '3-5'],
    text: 'Carrying out classroom responsibilities reliably is an ongoing goal for [Student].',
  },
  {
    id: 'behavior-growth-leadership-04',
    section: 'behavior',
    category: 'leadership',
    tone: 'growth',
    gradeBands: ['3-5', 'middle-upper'],
    text: "[Student] is working on inviting others' ideas when guiding a group.",
  },
  {
    id: 'behavior-growth-leadership-05',
    section: 'behavior',
    category: 'leadership',
    tone: 'growth',
    gradeBands: ['3-5', 'middle-upper'],
    text: '[Student] is working on raising concerns respectfully and working toward fair solutions.',
  },
  {
    id: 'behavior-growth-leadership-06',
    section: 'behavior',
    category: 'leadership',
    tone: 'growth',
    gradeBands: ['3-5', 'middle-upper'],
    text: '[Student] takes on leadership readily and is learning to hand the role to others as well.',
  },
  {
    id: 'behavior-positive-independence-01',
    section: 'behavior',
    category: 'independence',
    tone: 'positive',
    gradeBands: ['k-2', '3-5', 'middle-upper'],
    text: '[Student] begins work promptly once an activity is introduced.',
  },
  {
    id: 'behavior-positive-independence-02',
    section: 'behavior',
    category: 'independence',
    tone: 'positive',
    gradeBands: ['preschool', 'k-2', '3-5'],
    text: '[Student] gathers the materials they need and sets up for work independently.',
  },
  {
    id: 'behavior-positive-independence-03',
    section: 'behavior',
    category: 'independence',
    tone: 'positive',
    gradeBands: ['3-5', 'middle-upper'],
    text: 'When [Student] hits a difficulty, they try a strategy or two before seeking help.',
  },
  {
    id: 'behavior-positive-independence-04',
    section: 'behavior',
    category: 'independence',
    tone: 'positive',
    gradeBands: ['3-5', 'middle-upper'],
    text: '[Student] checks over their work before considering it finished.',
  },
  {
    id: 'behavior-positive-independence-05',
    section: 'behavior',
    category: 'independence',
    tone: 'positive',
    gradeBands: ['3-5', 'middle-upper'],
    text: '[Student] uses work time effectively and paces themselves through the task.',
  },
  {
    id: 'behavior-positive-independence-06',
    section: 'behavior',
    category: 'independence',
    tone: 'positive',
    gradeBands: ['preschool', 'k-2', '3-5'],
    text: '[Student] follows classroom routines with increasing independence.',
  },
  {
    id: 'behavior-positive-independence-07',
    section: 'behavior',
    category: 'independence',
    tone: 'positive',
    gradeBands: ['k-2', '3-5', 'middle-upper'],
    text: '[Student] recognizes when they need help and asks for it clearly.',
  },
  {
    id: 'behavior-positive-independence-08',
    section: 'behavior',
    category: 'independence',
    tone: 'positive',
    gradeBands: ['3-5', 'middle-upper'],
    text: 'When [Student] asks for help, they explain what they already tried and where they became unsure.',
  },
  {
    id: 'behavior-positive-independence-09',
    section: 'behavior',
    category: 'independence',
    tone: 'positive',
    gradeBands: ['k-2', '3-5', 'middle-upper'],
    text: '[Student] applies familiar routines appropriately in new situations.',
  },
  {
    id: 'behavior-growth-independence-01',
    section: 'behavior',
    category: 'independence',
    tone: 'growth',
    gradeBands: ['k-2', '3-5', 'middle-upper'],
    text: 'Beginning a task promptly after instructions are given is an area [Student] is continuing to develop.',
  },
  {
    id: 'behavior-growth-independence-02',
    section: 'behavior',
    category: 'independence',
    tone: 'growth',
    gradeBands: ['preschool', 'k-2', '3-5'],
    text: 'Gathering materials and setting up for work independently is an ongoing goal for [Student].',
  },
  {
    id: 'behavior-growth-independence-03',
    section: 'behavior',
    category: 'independence',
    tone: 'growth',
    gradeBands: ['3-5', 'middle-upper'],
    text: '[Student] is working on trying a strategy independently before asking for help.',
  },
  {
    id: 'behavior-growth-independence-04',
    section: 'behavior',
    category: 'independence',
    tone: 'growth',
    gradeBands: ['3-5', 'middle-upper'],
    text: 'Reviewing work before turning it in is a habit [Student] continues to build.',
  },
  {
    id: 'behavior-growth-independence-05',
    section: 'behavior',
    category: 'independence',
    tone: 'growth',
    gradeBands: ['3-5', 'middle-upper'],
    text: '[Student] is working on pacing themselves so they can finish within the time available.',
  },
  {
    id: 'behavior-growth-independence-06',
    section: 'behavior',
    category: 'independence',
    tone: 'growth',
    gradeBands: ['preschool', 'k-2', '3-5'],
    text: '[Student] is working on following classroom routines with fewer reminders.',
  },
  {
    id: 'behavior-growth-independence-07',
    section: 'behavior',
    category: 'independence',
    tone: 'growth',
    gradeBands: ['k-2', '3-5', 'middle-upper'],
    text: 'Identifying what help is needed before asking is a skill [Student] is continuing to develop.',
  },
  {
    id: 'behavior-growth-independence-08',
    section: 'behavior',
    category: 'independence',
    tone: 'growth',
    gradeBands: ['k-2', '3-5'],
    text: 'After making a mistake, [Student] sometimes pauses until an adult checks in before continuing.',
  },
  {
    id: 'behavior-growth-independence-09',
    section: 'behavior',
    category: 'independence',
    tone: 'growth',
    gradeBands: ['k-2', '3-5', 'middle-upper'],
    text: 'At times, [Student] moves on to a new task before completing the one already underway.',
  },
  {
    id: 'behavior-positive-effort-and-motivation-01',
    section: 'behavior',
    category: 'effort-and-motivation',
    tone: 'positive',
    gradeBands: ['k-2', '3-5', 'middle-upper'],
    text: 'When a task becomes difficult, [Student] keeps working at it rather than setting it aside.',
  },
  {
    id: 'behavior-positive-effort-and-motivation-02',
    section: 'behavior',
    category: 'effort-and-motivation',
    tone: 'positive',
    gradeBands: ['3-5', 'middle-upper'],
    text: '[Student] continues to work carefully in subjects that require more effort from them.',
  },
  {
    id: 'behavior-positive-effort-and-motivation-03',
    section: 'behavior',
    category: 'effort-and-motivation',
    tone: 'positive',
    gradeBands: ['3-5', 'middle-upper'],
    text: '[Student] takes feedback seriously and uses it to improve their work.',
  },
  {
    id: 'behavior-positive-effort-and-motivation-04',
    section: 'behavior',
    category: 'effort-and-motivation',
    tone: 'positive',
    gradeBands: ['k-2', '3-5', 'middle-upper'],
    text: '[Student] takes the time to do their work carefully rather than rushing to finish.',
  },
  {
    id: 'behavior-positive-effort-and-motivation-05',
    section: 'behavior',
    category: 'effort-and-motivation',
    tone: 'positive',
    gradeBands: ['k-2', '3-5', 'middle-upper'],
    text: '[Student] is willing to attempt a task even when they are unsure of the outcome.',
  },
  {
    id: 'behavior-positive-effort-and-motivation-06',
    section: 'behavior',
    category: 'effort-and-motivation',
    tone: 'positive',
    gradeBands: ['k-2', '3-5', 'middle-upper'],
    text: '[Student] regularly brings consistent effort to their classroom work.',
  },
  {
    id: 'behavior-positive-effort-and-motivation-07',
    section: 'behavior',
    category: 'effort-and-motivation',
    tone: 'positive',
    gradeBands: ['preschool', 'k-2', '3-5'],
    text: '[Student] completes their work with care and is eager to share the result.',
  },
  {
    id: 'behavior-positive-effort-and-motivation-08',
    section: 'behavior',
    category: 'effort-and-motivation',
    tone: 'positive',
    gradeBands: ['3-5', 'middle-upper'],
    text: '[Student] sustains their effort across multi-day projects and assignments.',
  },
  {
    id: 'behavior-positive-effort-and-motivation-09',
    section: 'behavior',
    category: 'effort-and-motivation',
    tone: 'positive',
    gradeBands: ['3-5', 'middle-upper'],
    text: '[Student] asks for more challenging work when they are ready for it.',
  },
  {
    id: 'behavior-positive-effort-and-motivation-10',
    section: 'behavior',
    category: 'effort-and-motivation',
    tone: 'positive',
    gradeBands: ['3-5', 'middle-upper'],
    text: '[Student] returns to completed work to revise and strengthen it.',
  },
  {
    id: 'behavior-positive-effort-and-motivation-11',
    section: 'behavior',
    category: 'effort-and-motivation',
    tone: 'positive',
    gradeBands: ['k-2', '3-5', 'middle-upper'],
    text: '[Student] approaches new material with genuine curiosity and willingness to engage.',
  },
  {
    id: 'behavior-growth-effort-and-motivation-01',
    section: 'behavior',
    category: 'effort-and-motivation',
    tone: 'growth',
    gradeBands: ['k-2', '3-5', 'middle-upper'],
    text: 'Persisting when a task becomes difficult is an area [Student] is continuing to develop.',
  },
  {
    id: 'behavior-growth-effort-and-motivation-02',
    section: 'behavior',
    category: 'effort-and-motivation',
    tone: 'growth',
    gradeBands: ['3-5', 'middle-upper'],
    text: 'Bringing consistent effort to less-preferred subjects is an ongoing goal for [Student].',
  },
  {
    id: 'behavior-growth-effort-and-motivation-03',
    section: 'behavior',
    category: 'effort-and-motivation',
    tone: 'growth',
    gradeBands: ['3-5', 'middle-upper'],
    text: '[Student] is working on using feedback to revise and strengthen their work.',
  },
  {
    id: 'behavior-growth-effort-and-motivation-04',
    section: 'behavior',
    category: 'effort-and-motivation',
    tone: 'growth',
    gradeBands: ['k-2', '3-5', 'middle-upper'],
    text: "[Student]'s finished work would better show what they can do with a slower, steadier pace.",
  },
  {
    id: 'behavior-growth-effort-and-motivation-05',
    section: 'behavior',
    category: 'effort-and-motivation',
    tone: 'growth',
    gradeBands: ['k-2', '3-5', 'middle-upper'],
    text: 'Attempting a task without being certain of the outcome is a skill [Student] continues to build.',
  },
  {
    id: 'behavior-growth-effort-and-motivation-06',
    section: 'behavior',
    category: 'effort-and-motivation',
    tone: 'growth',
    gradeBands: ['k-2', '3-5', 'middle-upper'],
    text: '[Student] is working toward more consistent effort across subjects and activities.',
  },
  {
    id: 'behavior-growth-effort-and-motivation-07',
    section: 'behavior',
    category: 'effort-and-motivation',
    tone: 'growth',
    gradeBands: ['k-2', '3-5', 'middle-upper'],
    text: '[Student] is working on completing each part of a task and communicating their thinking clearly.',
  },
  {
    id: 'behavior-growth-effort-and-motivation-08',
    section: 'behavior',
    category: 'effort-and-motivation',
    tone: 'growth',
    gradeBands: ['3-5', 'middle-upper'],
    text: 'Maintaining effort across longer projects is an area [Student] is continuing to develop.',
  },
  {
    id: 'behavior-growth-effort-and-motivation-09',
    section: 'behavior',
    category: 'effort-and-motivation',
    tone: 'growth',
    gradeBands: ['3-5', 'middle-upper'],
    text: '[Student] is working on engaging with new material before deciding whether it interests them.',
  },
  {
    id: 'behavior-positive-participation-01',
    section: 'behavior',
    category: 'participation',
    tone: 'positive',
    gradeBands: ['k-2', '3-5', 'middle-upper'],
    text: '[Student] contributes thoughtfully to whole-group discussions.',
  },
  {
    id: 'behavior-positive-participation-02',
    section: 'behavior',
    category: 'participation',
    tone: 'positive',
    gradeBands: ['k-2', '3-5', 'middle-upper'],
    text: 'In small groups and with a partner, [Student] offers ideas and joins the conversation easily.',
  },
  {
    id: 'behavior-positive-participation-03',
    section: 'behavior',
    category: 'participation',
    tone: 'positive',
    gradeBands: ['k-2', '3-5', 'middle-upper'],
    text: '[Student] asks thoughtful questions when something is unclear.',
  },
  {
    id: 'behavior-positive-participation-04',
    section: 'behavior',
    category: 'participation',
    tone: 'positive',
    gradeBands: ['3-5', 'middle-upper'],
    text: '[Student] listens closely to classmates and builds on what they have said.',
  },
  {
    id: 'behavior-positive-participation-05',
    section: 'behavior',
    category: 'participation',
    tone: 'positive',
    gradeBands: ['k-2', '3-5', 'middle-upper'],
    text: '[Student] shares their work and explains their thinking when invited.',
  },
  {
    id: 'behavior-positive-participation-06',
    section: 'behavior',
    category: 'participation',
    tone: 'positive',
    gradeBands: ['k-2', '3-5', 'middle-upper'],
    text: '[Student] participates even when they are not certain their answer is right.',
  },
  {
    id: 'behavior-positive-participation-07',
    section: 'behavior',
    category: 'participation',
    tone: 'positive',
    gradeBands: ['k-2', '3-5', 'middle-upper'],
    text: '[Student] is an attentive listener during discussions and responds to what classmates share.',
  },
  {
    id: 'behavior-positive-participation-08',
    section: 'behavior',
    category: 'participation',
    tone: 'positive',
    gradeBands: ['3-5', 'middle-upper'],
    text: '[Student] contributes consistently through written responses and classroom activities.',
  },
  {
    id: 'behavior-positive-participation-09',
    section: 'behavior',
    category: 'participation',
    tone: 'positive',
    gradeBands: ['3-5', 'middle-upper'],
    text: '[Student] engages with discussion across a range of subjects and topics.',
  },
  {
    id: 'behavior-positive-participation-10',
    section: 'behavior',
    category: 'participation',
    tone: 'positive',
    gradeBands: ['3-5', 'middle-upper'],
    text: '[Student] contributes to discussions while leaving room for classmates to share as well.',
  },
  {
    id: 'behavior-growth-participation-01',
    section: 'behavior',
    category: 'participation',
    tone: 'growth',
    gradeBands: ['k-2', '3-5', 'middle-upper'],
    text: 'During class discussions, [Student] is beginning to contribute their ideas more often.',
  },
  {
    id: 'behavior-growth-participation-02',
    section: 'behavior',
    category: 'participation',
    tone: 'growth',
    gradeBands: ['k-2', '3-5', 'middle-upper'],
    text: '[Student] is working on contributing more actively during small-group and partner work.',
  },
  {
    id: 'behavior-growth-participation-03',
    section: 'behavior',
    category: 'participation',
    tone: 'growth',
    gradeBands: ['k-2', '3-5', 'middle-upper'],
    text: '[Student] is working on asking for clarification when they are unsure how to proceed.',
  },
  {
    id: 'behavior-growth-participation-04',
    section: 'behavior',
    category: 'participation',
    tone: 'growth',
    gradeBands: ['3-5', 'middle-upper'],
    text: "[Student] is working on responding to classmates' ideas rather than only offering their own.",
  },
  {
    id: 'behavior-growth-participation-05',
    section: 'behavior',
    category: 'participation',
    tone: 'growth',
    gradeBands: ['k-2', '3-5', 'middle-upper'],
    text: 'Sharing work and explaining their thinking aloud is a skill [Student] continues to build.',
  },
  {
    id: 'behavior-growth-participation-06',
    section: 'behavior',
    category: 'participation',
    tone: 'growth',
    gradeBands: ['k-2', '3-5', 'middle-upper'],
    text: 'When unsure of an answer, [Student] often holds back from contributing to the discussion.',
  },
  {
    id: 'behavior-growth-participation-07',
    section: 'behavior',
    category: 'participation',
    tone: 'growth',
    gradeBands: ['3-5', 'middle-upper'],
    text: '[Student] is working on participating through written responses and classroom activities.',
  },
  {
    id: 'behavior-growth-participation-08',
    section: 'behavior',
    category: 'participation',
    tone: 'growth',
    gradeBands: ['3-5', 'middle-upper'],
    text: 'Participating across all subjects, including less-preferred ones, is an ongoing goal for [Student].',
  },
  {
    id: 'behavior-growth-participation-09',
    section: 'behavior',
    category: 'participation',
    tone: 'growth',
    gradeBands: ['k-2', '3-5', 'middle-upper'],
    text: '[Student] contributes frequently during discussions and is learning to leave space for classmates to speak as well.',
  },
  {
    id: 'adhd-positive-attention-and-focus-01',
    section: 'adhd',
    category: 'attention-and-focus',
    tone: 'positive',
    gradeBands: ['k-2', '3-5', 'middle-upper'],
    text: 'When work is broken into shorter segments, [Student] sustains their attention through the full work period.',
  },
  {
    id: 'adhd-positive-attention-and-focus-02',
    section: 'adhd',
    category: 'attention-and-focus',
    tone: 'positive',
    gradeBands: ['3-5', 'middle-upper'],
    text: "When a topic captures [Student]'s attention, they stay engaged with the work for a sustained stretch.",
  },
  {
    id: 'adhd-positive-attention-and-focus-03',
    section: 'adhd',
    category: 'attention-and-focus',
    tone: 'positive',
    gradeBands: ['3-5', 'middle-upper'],
    text: '[Student] increasingly returns to the task independently when their attention has drifted.',
  },
  {
    id: 'adhd-positive-attention-and-focus-04',
    section: 'adhd',
    category: 'attention-and-focus',
    tone: 'positive',
    gradeBands: ['k-2', '3-5', 'middle-upper'],
    text: 'After a brief break or a chance to move, [Student] returns to their work and picks up where they left off.',
  },
  {
    id: 'adhd-positive-attention-and-focus-05',
    section: 'adhd',
    category: 'attention-and-focus',
    tone: 'positive',
    gradeBands: ['k-2', '3-5', 'middle-upper'],
    text: '[Student] focuses well in a quieter area of the room with less traffic around them.',
  },
  {
    id: 'adhd-positive-attention-and-focus-06',
    section: 'adhd',
    category: 'attention-and-focus',
    tone: 'positive',
    gradeBands: ['3-5', 'middle-upper'],
    text: '[Student] uses a written or visual reminder to keep track of where they are in a task.',
  },
  {
    id: 'adhd-positive-attention-and-focus-07',
    section: 'adhd',
    category: 'attention-and-focus',
    tone: 'positive',
    gradeBands: ['k-2', '3-5', 'middle-upper'],
    text: 'A brief check-in partway through a task helps [Student] re-engage and continue working.',
  },
  {
    id: 'adhd-positive-attention-and-focus-08',
    section: 'adhd',
    category: 'attention-and-focus',
    tone: 'positive',
    gradeBands: ['k-2', '3-5'],
    text: '[Student] follows along more consistently when they can move or keep their hands busy while listening.',
  },
  {
    id: 'adhd-positive-attention-and-focus-09',
    section: 'adhd',
    category: 'attention-and-focus',
    tone: 'positive',
    gradeBands: ['k-2', '3-5', 'middle-upper'],
    text: "[Student]'s attention has been more consistent over the past several months.",
  },
  {
    id: 'adhd-growth-attention-and-focus-01',
    section: 'adhd',
    category: 'attention-and-focus',
    tone: 'growth',
    gradeBands: ['3-5'],
    text: '[Student] is continuing to build stamina for maintaining attention during longer lessons and benefits from brief opportunities to reset and refocus.',
  },
  {
    id: 'adhd-growth-attention-and-focus-02',
    section: 'adhd',
    category: 'attention-and-focus',
    tone: 'growth',
    gradeBands: ['k-2', '3-5', 'middle-upper'],
    text: "[Student]'s attention varies across classroom activities from one day to the next.",
  },
  {
    id: 'adhd-growth-attention-and-focus-03',
    section: 'adhd',
    category: 'attention-and-focus',
    tone: 'growth',
    gradeBands: ['3-5', 'middle-upper'],
    text: 'Returning to the task independently before an adult prompt is a skill [Student] is developing.',
  },
  {
    id: 'adhd-growth-attention-and-focus-04',
    section: 'adhd',
    category: 'attention-and-focus',
    tone: 'growth',
    gradeBands: ['k-2', '3-5', 'middle-upper'],
    text: "Movement and sound nearby draw [Student]'s attention away from their work. A quieter area with less traffic may support their focus.",
  },
  {
    id: 'adhd-growth-attention-and-focus-05',
    section: 'adhd',
    category: 'attention-and-focus',
    tone: 'growth',
    gradeBands: ['k-2', '3-5', 'middle-upper'],
    text: 'A brief check-in partway through a task may support [Student] in returning their attention to the work.',
  },
  {
    id: 'adhd-growth-attention-and-focus-06',
    section: 'adhd',
    category: 'attention-and-focus',
    tone: 'growth',
    gradeBands: ['3-5', 'middle-upper'],
    text: '[Student] maintains attention within one activity more consistently than across several consecutive classroom tasks.',
  },
  {
    id: 'adhd-positive-task-completion-01',
    section: 'adhd',
    category: 'task-completion',
    tone: 'positive',
    gradeBands: ['k-2', '3-5', 'middle-upper'],
    text: '[Student] completes their assignments and turns them in.',
  },
  {
    id: 'adhd-positive-task-completion-02',
    section: 'adhd',
    category: 'task-completion',
    tone: 'positive',
    gradeBands: ['3-5', 'middle-upper'],
    text: 'Once [Student] begins a task, they carry it through to completion.',
  },
  {
    id: 'adhd-positive-task-completion-03',
    section: 'adhd',
    category: 'task-completion',
    tone: 'positive',
    gradeBands: ['3-5', 'middle-upper'],
    text: '[Student] breaks longer assignments into smaller parts and works through them one at a time.',
  },
  {
    id: 'adhd-positive-task-completion-04',
    section: 'adhd',
    category: 'task-completion',
    tone: 'positive',
    gradeBands: ['3-5', 'middle-upper'],
    text: '[Student] keeps a list of what they have finished and what still needs to be done.',
  },
  {
    id: 'adhd-positive-task-completion-05',
    section: 'adhd',
    category: 'task-completion',
    tone: 'positive',
    gradeBands: ['k-2', '3-5', 'middle-upper'],
    text: 'When [Student] has to leave a task unfinished, they come back to it at the next opportunity.',
  },
  {
    id: 'adhd-positive-task-completion-06',
    section: 'adhd',
    category: 'task-completion',
    tone: 'positive',
    gradeBands: ['k-2', '3-5', 'middle-upper'],
    text: '[Student] finishes more of their work when a task is divided into shorter segments.',
  },
  {
    id: 'adhd-positive-task-completion-07',
    section: 'adhd',
    category: 'task-completion',
    tone: 'positive',
    gradeBands: ['3-5', 'middle-upper'],
    text: '[Student] identifies a first step and gets started on their assignments.',
  },
  {
    id: 'adhd-growth-task-completion-01',
    section: 'adhd',
    category: 'task-completion',
    tone: 'growth',
    gradeBands: ['k-2', '3-5', 'middle-upper'],
    text: 'Finishing assignments within the time available is an area [Student] is developing. Dividing a task into shorter segments may support this.',
  },
  {
    id: 'adhd-growth-task-completion-02',
    section: 'adhd',
    category: 'task-completion',
    tone: 'growth',
    gradeBands: ['k-2', '3-5', 'middle-upper'],
    text: '[Student] often begins their work but does not always carry it through to completion.',
  },
  {
    id: 'adhd-growth-task-completion-03',
    section: 'adhd',
    category: 'task-completion',
    tone: 'growth',
    gradeBands: ['3-5', 'middle-upper'],
    text: '[Student] completes their work but does not always turn it in. A routine for submitting finished assignments may support this.',
  },
  {
    id: 'adhd-growth-task-completion-04',
    section: 'adhd',
    category: 'task-completion',
    tone: 'growth',
    gradeBands: ['3-5', 'middle-upper'],
    text: "Getting started is a recurring challenge across [Student]'s assignments. Identifying a clear first step helps them begin.",
  },
  {
    id: 'adhd-growth-task-completion-05',
    section: 'adhd',
    category: 'task-completion',
    tone: 'growth',
    gradeBands: ['k-2', '3-5', 'middle-upper'],
    text: 'Coming back to unfinished work is a skill [Student] is developing. A set time to catch up may support this.',
  },
  {
    id: 'adhd-positive-self-regulation-strategies-01',
    section: 'adhd',
    category: 'self-regulation-strategies',
    tone: 'positive',
    gradeBands: ['k-2', '3-5'],
    text: '[Student] has learned to ask for a movement break before frustration builds, demonstrating growing self-awareness and self-advocacy.',
  },
  {
    id: 'adhd-positive-self-regulation-strategies-02',
    section: 'adhd',
    category: 'self-regulation-strategies',
    tone: 'positive',
    gradeBands: ['k-2', '3-5', 'middle-upper'],
    text: 'When [Student] needs a reset, they take appropriate steps to request or use one.',
  },
  {
    id: 'adhd-positive-self-regulation-strategies-03',
    section: 'adhd',
    category: 'self-regulation-strategies',
    tone: 'positive',
    gradeBands: ['3-5', 'middle-upper'],
    text: '[Student] can say what helps them focus, and they ask for it when they need it.',
  },
  {
    id: 'adhd-positive-self-regulation-strategies-04',
    section: 'adhd',
    category: 'self-regulation-strategies',
    tone: 'positive',
    gradeBands: ['3-5', 'middle-upper'],
    text: 'Given a few options, [Student] chooses the one that fits what they need at the time.',
  },
  {
    id: 'adhd-positive-self-regulation-strategies-05',
    section: 'adhd',
    category: 'self-regulation-strategies',
    tone: 'positive',
    gradeBands: ['k-2', '3-5', 'middle-upper'],
    text: '[Student] uses the strategies that work for them without waiting to be prompted.',
  },
  {
    id: 'adhd-positive-self-regulation-strategies-06',
    section: 'adhd',
    category: 'self-regulation-strategies',
    tone: 'positive',
    gradeBands: ['3-5', 'middle-upper'],
    text: 'When a familiar challenge comes up in a new setting, [Student] chooses a strategy that has helped them before.',
  },
  {
    id: 'adhd-growth-self-regulation-strategies-01',
    section: 'adhd',
    category: 'self-regulation-strategies',
    tone: 'growth',
    gradeBands: ['k-2', '3-5', 'middle-upper'],
    text: 'After a strategy is suggested, [Student] uses it effectively. Choosing and using a strategy independently is the next skill they are developing.',
  },
  {
    id: 'adhd-growth-self-regulation-strategies-02',
    section: 'adhd',
    category: 'self-regulation-strategies',
    tone: 'growth',
    gradeBands: ['k-2', '3-5', 'middle-upper'],
    text: 'Asking for a break before continuing becomes difficult is a skill [Student] is building.',
  },
  {
    id: 'adhd-growth-self-regulation-strategies-03',
    section: 'adhd',
    category: 'self-regulation-strategies',
    tone: 'growth',
    gradeBands: ['3-5', 'middle-upper'],
    text: '[Student] is learning to put words to what they need in the moment. Reviewing a few options ahead of time may help them communicate their choice.',
  },
  {
    id: 'adhd-growth-self-regulation-strategies-04',
    section: 'adhd',
    category: 'self-regulation-strategies',
    tone: 'growth',
    gradeBands: ['k-2', '3-5', 'middle-upper'],
    text: '[Student] is learning to use familiar strategies across different parts of the school day.',
  },
  {
    id: 'adhd-positive-impulse-control-01',
    section: 'adhd',
    category: 'impulse-control',
    tone: 'positive',
    gradeBands: ['3-5', 'middle-upper'],
    text: 'When [Student] has an idea mid-lesson, they are increasingly able to hold it and come back to it.',
  },
  {
    id: 'adhd-positive-impulse-control-02',
    section: 'adhd',
    category: 'impulse-control',
    tone: 'positive',
    gradeBands: ['k-2', '3-5', 'middle-upper'],
    text: 'When unsure whether it is the right time to act, [Student] pauses and asks before proceeding.',
  },
  {
    id: 'adhd-positive-impulse-control-03',
    section: 'adhd',
    category: 'impulse-control',
    tone: 'positive',
    gradeBands: ['k-2', '3-5', 'middle-upper'],
    text: '[Student] uses movement opportunities appropriately and returns to the group ready to rejoin the activity.',
  },
  {
    id: 'adhd-positive-impulse-control-04',
    section: 'adhd',
    category: 'impulse-control',
    tone: 'positive',
    gradeBands: ['3-5', 'middle-upper'],
    text: '[Student] takes a moment to look over what is being asked before beginning to answer.',
  },
  {
    id: 'adhd-growth-impulse-control-01',
    section: 'adhd',
    category: 'impulse-control',
    tone: 'growth',
    gradeBands: ['k-2', '3-5'],
    text: 'Waiting for a turn to speak is an ongoing goal; [Student] is working on raising a hand instead of calling out an answer.',
  },
  {
    id: 'adhd-growth-impulse-control-02',
    section: 'adhd',
    category: 'impulse-control',
    tone: 'growth',
    gradeBands: ['3-5', 'middle-upper'],
    text: '[Student] sometimes begins responding before reviewing the full task. Pausing to look over what is being asked is a skill they are developing.',
  },
  {
    id: 'adhd-growth-impulse-control-03',
    section: 'adhd',
    category: 'impulse-control',
    tone: 'growth',
    gradeBands: ['k-2', '3-5', 'middle-upper'],
    text: '[Student] moves around the room at times when the class is working together. More frequent movement opportunities might help them get what they need while staying with the lesson.',
  },
  {
    id: 'adhd-growth-impulse-control-04',
    section: 'adhd',
    category: 'impulse-control',
    tone: 'growth',
    gradeBands: ['k-2', '3-5', 'middle-upper'],
    text: '[Student] is developing the ability to join conversations without speaking over others.',
  },
  {
    id: 'adhd-positive-organization-01',
    section: 'adhd',
    category: 'organization',
    tone: 'positive',
    gradeBands: ['3-5', 'middle-upper'],
    text: "[Student]'s organizational habits help them locate materials and be ready to begin their work.",
  },
  {
    id: 'adhd-positive-organization-02',
    section: 'adhd',
    category: 'organization',
    tone: 'positive',
    gradeBands: ['k-2', '3-5', 'middle-upper'],
    text: '[Student] can find the materials they need when it is time to start working.',
  },
  {
    id: 'adhd-positive-organization-03',
    section: 'adhd',
    category: 'organization',
    tone: 'positive',
    gradeBands: ['3-5', 'middle-upper'],
    text: '[Student] has a system that works for them, and they use it consistently.',
  },
  {
    id: 'adhd-positive-organization-04',
    section: 'adhd',
    category: 'organization',
    tone: 'positive',
    gradeBands: ['3-5', 'middle-upper'],
    text: '[Student] records their assignments and due dates and refers back to what they have written down.',
  },
  {
    id: 'adhd-positive-organization-05',
    section: 'adhd',
    category: 'organization',
    tone: 'positive',
    gradeBands: ['k-2', '3-5', 'middle-upper'],
    text: '[Student] keeps unfinished work somewhere they can find it again.',
  },
  {
    id: 'adhd-positive-organization-06',
    section: 'adhd',
    category: 'organization',
    tone: 'positive',
    gradeBands: ['k-2', '3-5', 'middle-upper'],
    text: '[Student] keeps track of papers as they move through each stage of an assignment.',
  },
  {
    id: 'adhd-positive-organization-07',
    section: 'adhd',
    category: 'organization',
    tone: 'positive',
    gradeBands: ['k-2', '3-5', 'middle-upper'],
    text: 'At the end of a work period, [Student] puts materials away and prepares what they will need next.',
  },
  {
    id: 'adhd-growth-organization-01',
    section: 'adhd',
    category: 'organization',
    tone: 'growth',
    gradeBands: ['k-2', '3-5', 'middle-upper'],
    text: 'Papers are sometimes misplaced between the time [Student] receives them and the time they are needed.',
  },
  {
    id: 'adhd-growth-organization-02',
    section: 'adhd',
    category: 'organization',
    tone: 'growth',
    gradeBands: ['3-5', 'middle-upper'],
    text: 'Keeping track of assignments and what is still outstanding is an area [Student] is developing. A written record of tasks and due dates may support this.',
  },
  {
    id: 'adhd-growth-organization-03',
    section: 'adhd',
    category: 'organization',
    tone: 'growth',
    gradeBands: ['k-2', '3-5', 'middle-upper'],
    text: "Locating materials takes time away from [Student]'s work. A consistent place to keep frequently used items may support this.",
  },
  {
    id: 'adhd-growth-organization-04',
    section: 'adhd',
    category: 'organization',
    tone: 'growth',
    gradeBands: ['3-5', 'middle-upper'],
    text: 'Keeping the parts of a longer project together across several days is a skill [Student] is developing.',
  },
  {
    id: 'adhd-growth-organization-05',
    section: 'adhd',
    category: 'organization',
    tone: 'growth',
    gradeBands: ['k-2', '3-5', 'middle-upper'],
    text: '[Student] is developing a more consistent system for keeping track of materials that travel between home and school. A packing checklist may support this.',
  },
  {
    id: 'preschool-positive-self-help-skills-01',
    section: 'preschool',
    category: 'self-help-skills',
    tone: 'positive',
    gradeBands: ['preschool'],
    text: '[Student] puts on their own coat and shoes at pickup time without being reminded.',
  },
  {
    id: 'preschool-growth-play-and-cooperation-01',
    section: 'preschool',
    category: 'play-and-cooperation',
    tone: 'growth',
    gradeBands: ['preschool'],
    text: 'Sharing toys during center time is still a work in progress; [Student] benefits from gentle reminders and support taking turns.',
  },
  {
    id: 'preschool-positive-early-literacy-01',
    section: 'preschool',
    category: 'early-literacy',
    tone: 'positive',
    gradeBands: ['preschool'],
    text: 'During story time, [Student] points out letters from their own name on the page and gets excited every time.',
  },
  {
    id: 'preschool-growth-gross-and-fine-motor-01',
    section: 'preschool',
    category: 'gross-and-fine-motor',
    tone: 'growth',
    gradeBands: ['preschool'],
    text: 'Holding scissors and cutting along a line is still tricky for [Student]; more practice with playdough and tongs would help build hand strength.',
  },
  {
    id: 'academics-positive-reading-01',
    section: 'academics',
    category: 'reading',
    tone: 'positive',
    gradeBands: ['k-2', '3-5'],
    text: '[Student] reads with real expression now, changing their voice for different characters without being asked.',
  },
  {
    id: 'academics-growth-writing-01',
    section: 'academics',
    category: 'writing',
    tone: 'growth',
    gradeBands: ['3-5', 'middle-upper'],
    text: 'Getting ideas onto the page is harder than talking through them out loud; [Student] benefits from saying a sentence aloud before writing it down.',
  },
  {
    id: 'academics-positive-math-01',
    section: 'academics',
    category: 'math',
    tone: 'positive',
    gradeBands: ['3-5'],
    text: 'Multi-step word problems are an area where [Student] tends to shine, working through each step methodically.',
  },
  {
    id: 'academics-growth-general-work-habits-01',
    section: 'academics',
    category: 'general-work-habits',
    tone: 'growth',
    gradeBands: ['middle-upper'],
    text: "The quality of [Student]'s completed work is consistently strong; building a more consistent habit of submitting homework is the next goal.",
  },
  {
    id: 'social-emotional-positive-empathy-and-relationships-01',
    section: 'social-emotional',
    category: 'empathy-and-relationships',
    tone: 'positive',
    gradeBands: ['k-2', '3-5'],
    text: 'When a classmate is upset, [Student] is quick to notice and check in, showing real care for others.',
  },
  {
    id: 'social-emotional-growth-emotional-regulation-01',
    section: 'social-emotional',
    category: 'emotional-regulation',
    tone: 'growth',
    gradeBands: ['k-2'],
    text: 'Big feelings can be overwhelming for [Student] in the moment; continuing to practice naming emotions can support stronger emotional regulation.',
  },
  {
    id: 'social-emotional-positive-resilience-and-growth-mindset-01',
    section: 'social-emotional',
    category: 'resilience-and-growth-mindset',
    tone: 'positive',
    gradeBands: ['3-5', 'middle-upper'],
    text: "After a wrong answer, [Student]'s instinct is to try again rather than give up, which has become one of their real strengths this year.",
  },
];
